server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods "GET,POST,PATCH,DELETE,OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization,Content-Type,X-Hamman-Signature,Accept" always;

    if ($request_method = OPTIONS) { return 204; }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 60;
    }

    location ~ /\.(env|git) { deny all; }
}
